force-app/main/default/objects/Beat_Stop__c/Beat_Stop__c.object-meta.xml
<CustomObject>
    <label>Beat Stop</label>
    <pluralLabel>Beat Stops</pluralLabel>
    <description>Beat Stop</description>
    <nameField>
        <label>Beat Stop Name</label>
        <type>AutoNumber</type>
        <displayFormat>STP-{000000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat_Stop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <type>Lookup</type>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beat Stops</relationshipLabel>
    <relationshipName>Beat_Stops</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
</CustomField>

force-app/main/default/objects/Beat_Stop__c/fields/Sales_Beat__c.field-meta.xml
<CustomField>
    <fullName>Sales_Beat__c</fullName>
    <label>Sales Beat</label>
    <type>MasterDetail</type>
    <referenceTo>Sales_Beat__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <description>Sales Beat</description>
</CustomField>

force-app/main/default/objects/Sales_Beat__c/Sales_Beat__c.object-meta.xml
<CustomObject>
    <label>Sales Beat</label>
    <pluralLabel>Sales Beats</pluralLabel>
    <description>Sales Beat</description>
    <nameField>
        <label>Sales Beat Name</label>
        <type>AutoNumber</type>
        <displayFormat>SBT-{000000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DailyBeatServiceTest.cls
@IsTest
private class DailyBeatServiceTest {

    @IsTest static void generatesVisits() {
        User u = TestDataFactory.createUser('fs1');
        Account a = TestDataFactory.createAccount('Store');
        Sales_Beat__c b = TestDataFactory.createBeat(u.Id);
        insert new Beat_Stop__c(Sales_Beat__c = b.Id, Account__c = a.Id, Sequence__c = 1);
        Test.startTest();
        Integer n = DailyBeatService.generateToday();
        Test.stopTest();
        System.assert(n >= 1);
    }

}